//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLoveEmployeeManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Music
    {
        public int songID { get; set; }
        public string songTitle { get; set; }
        public string songAlbum { get; set; }
        public string songArtist { get; set; }
    }
}
